/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
import type * as utils from "./utils";
export type { utils };
export type { IMultiAsset } from "./IMultiAsset";
export type { MultiAssetToken } from "./MultiAssetToken";
