/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as multiAssetRendererUtilsSol from "./MultiAssetRendererUtils.sol";
export type { multiAssetRendererUtilsSol };
