/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721ReceiverMock } from "./ERC721ReceiverMock";
export type { MultiAssetTokenMock } from "./MultiAssetTokenMock";
export type { NonReceiverMock } from "./NonReceiverMock";
